// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sgalaxzbnwjwpltmpvmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNnYWxheHpibndqd3BsdG1wdm1nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNzQzNTcsImV4cCI6MjA2ODg1MDM1N30.AHNL0bjA836slloHLRvUrDjFYNY-NrAeFDYjNFHZoK0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});